### ISSUE TITLE
单条命令无法添加直播

### ISSUE THREAD

**Issue by lymweb** [woniuzfb/iptv#6]
官方提供的以下示例，运行后，会在/usr/local/iptv/live里增加相应文件夹，但ffmpeg没有启动，输入tv后没有查到该频道。

使用crf值控制视频质量:
tv -i http://xxx/xxx.ts -s 6 -o hbo1 -p hbo1 -q 15 -b 1500-1280x720 -z 'hbo直播1'

使用比特率控制视频质量[ 默认 ]:
tv -i http://xxx/xxx.ts -s 6 -o hbo2 -p hbo2 -b 900-1280x720 -z 'hbo直播2'

输入tv后，再按5，然后不停下一步，就可以增加直播。

**Comment by woniuzfb** [comment]
solved
